In [2]:
from sqlalchemy import create_engine
source = create_engine('mysql+mysqlconnector://test:test123@db/test')
import pandas as pd
pd.read_sql("select current_date", con=source)

  current_date
0   2021-02-04

In [2]:
pip install pyarrow

Requirement already satisfied: pyarrow in /opt/conda/lib/python3.8/site-packages (3.0.0)
Requirement already satisfied: numpy>=1.16.6 in /opt/conda/lib/python3.8/site-packages (from pyarrow) (1.20.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
pip install fastparquet

Collecting fastparquet
  Using cached fastparquet-0.5.0.tar.gz (120 kB)
Requirement already satisfied: pandas>=1.1.0 in /opt/conda/lib/python3.8/site-packages (from fastparquet) (1.2.1)
Requirement already satisfied: numba>=0.49 in /opt/conda/lib/python3.8/site-packages (from fastparquet) (0.52.0)
Requirement already satisfied: numpy>=1.11 in /opt/conda/lib/python3.8/site-packages (from fastparquet) (1.20.0)
Requirement already satisfied: thrift>=0.11.0 in /opt/conda/lib/python3.8/site-packages (from fastparquet) (0.13.0)
Requirement already satisfied: llvmlite<0.36,>=0.35.0 in /opt/conda/lib/python3.8/site-packages (from numba>=0.49->fastparquet) (0.35.0)
Requirement already satisfied: setuptools in /opt/conda/lib/python3.8/site-packages (from numba>=0.49->fastparquet) (49.6.0.post20210108)
Requirement already satisfied: python-dateutil>=2.7.3 in /opt/conda/lib/python3.8/site-packages (from pandas>=1.1.0->fastparquet) (2.8.1)
Requirement already satisfied: pytz>=2017.3 in /opt/conda/lib/python3.8/site-packages (from pandas>=1.1.0->fastparquet) (2020.5)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.8/site-packages (from python-dateutil>=2.7.3->pandas>=1.1.0->fastparquet) (1.15.0)
Building wheels for collected packages: fastparquet
  Building wheel for fastparquet (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /opt/conda/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-6xuo_g2b/fastparquet_0e2567320a5b415081dd3f0fecba0f07/setup.py'"'"'; __file__='"'"'/tmp/pip-install-6xuo_g2b/fastparquet_0e2567320a5b415081dd3f0fecba0f07/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-tozq99sc
       cwd: /tmp/pip-install-6xuo_g2b/fastparquet_0e2567320a5b415081dd3f0fecba0f07/
  Complete output (46 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.8
  creating build/lib.linux-x86_64-3.8/fastparquet
  copying fastparquet/writer.py -> build/lib.linux-x86_64-3.8/fastparquet
  copying fastparquet/thrift_structures.py -> build/lib.linux-x86_64-3.8/fastparquet
  copying fastparquet/core.py -> build/lib.linux-x86_64-3.8/fastparquet
  copying fastparquet/api.py -> build/lib.linux-x86_64-3.8/fastparquet
  copying fastparquet/encoding.py -> build/lib.linux-x86_64-3.8/fastparquet
  copying fastparquet/dataframe.py -> build/lib.linux-x86_64-3.8/fastparquet
  copying fastparquet/compression.py -> build/lib.linux-x86_64-3.8/fastparquet
  copying fastparquet/schema.py -> build/lib.linux-x86_64-3.8/fastparquet
  copying fastparquet/util.py -> build/lib.linux-x86_64-3.8/fastparquet
  copying fastparquet/__init__.py -> build/lib.linux-x86_64-3.8/fastparquet
  copying fastparquet/converted_types.py -> build/lib.linux-x86_64-3.8/fastparquet
  running egg_info
  writing fastparquet.egg-info/PKG-INFO
  writing dependency_links to fastparquet.egg-info/dependency_links.txt
  writing requirements to fastparquet.egg-info/requires.txt
  writing top-level names to fastparquet.egg-info/top_level.txt
  reading manifest file 'fastparquet.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  no previously-included directories found matching 'fastparquet/test/'
  no previously-included directories found matching 'test-data/'
  no previously-included directories found matching 'docs/'
  writing manifest file 'fastparquet.egg-info/SOURCES.txt'
  copying fastparquet/parquet.thrift -> build/lib.linux-x86_64-3.8/fastparquet
  copying fastparquet/speedups.c -> build/lib.linux-x86_64-3.8/fastparquet
  copying fastparquet/speedups.pyx -> build/lib.linux-x86_64-3.8/fastparquet
  creating build/lib.linux-x86_64-3.8/fastparquet/benchmarks
  copying fastparquet/benchmarks/columns.py -> build/lib.linux-x86_64-3.8/fastparquet/benchmarks
  creating build/lib.linux-x86_64-3.8/fastparquet/parquet_thrift
  copying fastparquet/parquet_thrift/__init__.py -> build/lib.linux-x86_64-3.8/fastparquet/parquet_thrift
  creating build/lib.linux-x86_64-3.8/fastparquet/parquet_thrift/parquet
  copying fastparquet/parquet_thrift/parquet/__init__.py -> build/lib.linux-x86_64-3.8/fastparquet/parquet_thrift/parquet
  copying fastparquet/parquet_thrift/parquet/constants.py -> build/lib.linux-x86_64-3.8/fastparquet/parquet_thrift/parquet
  copying fastparquet/parquet_thrift/parquet/ttypes.py -> build/lib.linux-x86_64-3.8/fastparquet/parquet_thrift/parquet
  running build_ext
  building 'fastparquet.speedups' extension
  creating build/temp.linux-x86_64-3.8
  creating build/temp.linux-x86_64-3.8/fastparquet
  gcc -pthread -B /opt/conda/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/opt/conda/include/python3.8 -I/opt/conda/lib/python3.8/site-packages/numpy/core/include -c fastparquet/speedups.c -o build/temp.linux-x86_64-3.8/fastparquet/speedups.o
  unable to execute 'gcc': No such file or directory
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for fastparquet
  Running setup.py clean for fastparquet
Failed to build fastparquet
Installing collected packages: fastparquet
    Running setup.py install for fastparquet ... error
    ERROR: Command errored out with exit status 1:
     command: /opt/conda/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-6xuo_g2b/fastparquet_0e2567320a5b415081dd3f0fecba0f07/setup.py'"'"'; __file__='"'"'/tmp/pip-install-6xuo_g2b/fastparquet_0e2567320a5b415081dd3f0fecba0f07/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-0ii8awce/install-record.txt --single-version-externally-managed --compile --install-headers /opt/conda/include/python3.8/fastparquet
         cwd: /tmp/pip-install-6xuo_g2b/fastparquet_0e2567320a5b415081dd3f0fecba0f07/
    Complete output (21 lines):
    running install
    running build
    running build_py
    running egg_info
    writing fastparquet.egg-info/PKG-INFO
    writing dependency_links to fastparquet.egg-info/dependency_links.txt
    writing requirements to fastparquet.egg-info/requires.txt
    writing top-level names to fastparquet.egg-info/top_level.txt
    reading manifest file 'fastparquet.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    no previously-included directories found matching 'fastparquet/test/'
    no previously-included directories found matching 'test-data/'
    no previously-included directories found matching 'docs/'
    writing manifest file 'fastparquet.egg-info/SOURCES.txt'
    running build_ext
    building 'fastparquet.speedups' extension
    creating build/temp.linux-x86_64-3.8
    creating build/temp.linux-x86_64-3.8/fastparquet
    gcc -pthread -B /opt/conda/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/opt/conda/include/python3.8 -I/opt/conda/lib/python3.8/site-packages/numpy/core/include -c fastparquet/speedups.c -o build/temp.linux-x86_64-3.8/fastparquet/speedups.o
    unable to execute 'gcc': No such file or directory
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /opt/conda/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-6xuo_g2b/fastparquet_0e2567320a5b415081dd3f0fecba0f07/setup.py'"'"'; __file__='"'"'/tmp/pip-install-6xuo_g2b/fastparquet_0e2567320a5b415081dd3f0fecba0f07/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-0ii8awce/install-record.txt --single-version-externally-managed --compile --install-headers /opt/conda/include/python3.8/fastparquet Check the logs for full command output.
Note: you may need to restart the kernel to use updated packages.

In [3]:

df = pd.read_parquet('data.parquet')
df.head()
df.dtypes

vendor_id                        object
pickup_at                datetime64[ns]
dropoff_at               datetime64[ns]
passenger_count                    int8
trip_distance                   float32
rate_code_id                     object
store_and_fwd_flag               object
pickup_location_id                int32
dropoff_location_id               int32
payment_type                     object
fare_amount                     float32
extra                           float32
mta_tax                         float32
tip_amount                      float32
tolls_amount                    float32
improvement_surcharge           float32
total_amount                    float32
congestion_surcharge            float32
dtype: object

In [5]:
# todo esta bien, no hay nans

In [4]:
data = df.iloc[0:20,:]
data.to_sql('data', con=source, schema='test', if_exists='replace', index=False)

In [5]:
pd.read_sql_query('SELECT * FROM data', con=source)

,vendor_id,pickup_at,dropoff_at,passenger_count,trip_distance,rate_code_id,store_and_fwd_flag,pickup_location_id,dropoff_location_id,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1,2019-06-01 00:55:13,2019-06-01 00:56:17,1,0.00,1,N,145,145,2,3.0,0.5,0.5,0.00,0.0,0.3,4.30,0.0
1,1,2019-06-01 00:06:31,2019-06-01 00:06:52,1,0.00,1,N,262,263,2,2.5,3.0,0.5,0.00,0.0,0.3,6.30,2.5
2,1,2019-06-01 00:17:05,2019-06-01 00:36:38,1,4.40,1,N,74,7,2,17.5,0.5,0.5,0.00,0.0,0.3,18.80,0.0
3,1,2019-06-01 00:59:02,2019-06-01 00:59:12,0,0.80,1,N,145,145,2,2.5,1.0,0.5,0.00,0.0,0.3,4.30,0.0
4,1,2019-06-01 00:03:25,2019-06-01 00:15:42,1,1.70,1,N,113,148,1,9.5,3.0,0.5,2.65,0.0,0.3,15.95,2.5
5,1,2019-06-01 00:28:31,2019-06-01 00:39:23,2,1.60,1,N,79,125,1,9.5,3.0,0.5,1.00,0.0,0.3,14.30,2.5
6,1,2019-06-01 00:46:46,2019-06-01 00:50:55,4,0.60,1,N,211,148,2,4.5,3.0,0.5,0.00,0.0,0.3,8.30,2.5
7,1,2019-06-01 00:54:49,2019-06-01 01:02:57,2,1.20,1,N,79,249,1,7.5,3.0,0.5,1.00,0.0,0.3,12.30,2.5
8,1,2019-06-01 00:09:57,2019-06-01 00:25:54,2,2.00,1,N,158,68,2,11.5,3.0,0.5,0.00,0.0,0.3,15.30,2.5
9,1,2019-06-01 00:29:12,2019-06-01 01:03:13,1,8.60,1,N,186,243,1,31.5,3.0,0.5,7.05,0.0,0.3,42.35,2.5
10,2,2019-06-01 00:01:48,2019-06-01 00:16:06,1,1.74,1,N,107,148,1,11.0,0.5,0.5,2.96,0.0,0.3,17.76,2.5
11,2,2019-06-01 00:17:41,2019-06-01 00:30:22,1,2.22,1,N,148,137,2,10.5,0.5,0.5,0.00,0.0,0.3,14.30,2.5
12,2,2019-06-01 00:33:26,2019-06-01 00:39:18,1,1.20,1,N,137,170,1,6.0,0.5,0.5,2.45,0.0,0.3,12.25,2.5
13,1,2019-06-01 00:01:42,2019-06-01 00:06:14,1,0.70,1,N,229,141,1,5.5,3.0,0.5,1.70,0.0,0.3,11.00,2.5
14,2,2019-06-01 00:20:08,2019-06-01 00:28:56,1,1.83,1,N,113,161,1,8.0,0.5,0.5,1.00,0.0,0.3,12.80,2.5
15,2,2019-06-01 00:30:40,2019-06-01 01:08:12,1,5.11,1,N,230,229,1,25.0,0.5,0.5,7.20,0.0,0.3,36.00,2.5
16,1,2019-06-01 00:17:06,2019-06-01 00:46:21,1,4.80,1,N,7,170,3,21.0,3.0,0.5,0.00,0.0,0.3,24.80,2.5
17,1,2019-06-01 00:47:52,2019-06-01 01:04:19,1,5.20,1,N,170,42,1,16.5,3.0,0.5,4.05,0.0,0.3,24.35,2.5
18,2,2019-06-01 00:05:51,2019-06-01 00:30:45,1,9.05,1,N,138,189,1,28.5,0.5,0.5,7.45,0.0,0.3,37.25,0.0
19,2,2019-06-01 00:36:38,2019-06-01 00:57:43,1,4.07,1,N,97,89,1,16.5,0.5,0.5,3.56,0.0,0.3,21.36,0.0